### ISSUE TITLE
add your slides?

### ISSUE THREAD

**Issue by cpanse** [coreforlife/meetings#5]

**Comment by FranzNepthun** [comment]
[C4L_Barcelona_V1.pptx](https://github.com/coreforlife/meetings/files/3697307/C4L_Barcelona_V1.pptx)

Here they are...

**Comment by cpanse** [comment]
@fstein can you make a PDF?

**Comment by fstein** [comment]
[C4L_Barcelona_V1.pdf](https://github.com/coreforlife/meetings/files/3697789/C4L_Barcelona_V1.pdf)
Sure

**Comment by rolivella** [comment]
[C4L_BCN_2019_QCloud_C4L_API_MarcSerret.pdf](https://github.com/coreforlife/meetings/files/3706916/C4L_BCN_2019_QCloud_C4L_API_MarcSerret.pdf)
[C4L_BCN_2019_QCloud_RogerOlivella.pdf](https://github.com/coreforlife/meetings/files/3706917/C4L_BCN_2019_QCloud_RogerOlivella.pdf)
[C4L_BCN_2019_QCloud_general_API_MarcSerret.pdf](https://github.com/coreforlife/meetings/files/3706918/C4L_BCN_2019_QCloud_general_API_MarcSerret.pdf)
[C4L_BCN_2019_Telegram_MarcSerret.pdf](https://github.com/coreforlife/meetings/files/3706919/C4L_BCN_2019_Telegram_MarcSerret.pdf)

**Comment by ppoullet** [comment]
From Cuire:
[C4L_BioinfoCurie_20191007.pdf](https://github.com/coreforlife/meetings/files/3720358/C4L_BioinfoCurie_20191007.pdf)
